version: "3.7"
services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - .data/data.ms:/data.ms
    environment:
      MEILI_NO_ANALYTICS: true
      MEILI_MASTER_KEY: "masterKey"
      MEILI_ENV: "development"
      MEILI_HTTP_PAYLOAD_SIZE_LIMIT: 304857600